package com.anju.yyk.common.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.anju.yyk.common.db.CommonOrderConfig;
import com.anju.yyk.common.db.CommonType;

import com.anju.yyk.common.db.CommonOrderConfigDao;
import com.anju.yyk.common.db.CommonTypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commonOrderConfigDaoConfig;
    private final DaoConfig commonTypeDaoConfig;

    private final CommonOrderConfigDao commonOrderConfigDao;
    private final CommonTypeDao commonTypeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commonOrderConfigDaoConfig = daoConfigMap.get(CommonOrderConfigDao.class).clone();
        commonOrderConfigDaoConfig.initIdentityScope(type);

        commonTypeDaoConfig = daoConfigMap.get(CommonTypeDao.class).clone();
        commonTypeDaoConfig.initIdentityScope(type);

        commonOrderConfigDao = new CommonOrderConfigDao(commonOrderConfigDaoConfig, this);
        commonTypeDao = new CommonTypeDao(commonTypeDaoConfig, this);

        registerDao(CommonOrderConfig.class, commonOrderConfigDao);
        registerDao(CommonType.class, commonTypeDao);
    }
    
    public void clear() {
        commonOrderConfigDaoConfig.clearIdentityScope();
        commonTypeDaoConfig.clearIdentityScope();
    }

    public CommonOrderConfigDao getCommonOrderConfigDao() {
        return commonOrderConfigDao;
    }

    public CommonTypeDao getCommonTypeDao() {
        return commonTypeDao;
    }

}
